### ISSUE TITLE
Support of videojs 5.4.3

### ISSUE THREAD

**Issue by spuyet** [benjipott/video.js-dailymotion#23]
Hi,

The plugin does not work with the latest version of video-js, you plan to update it ?

Thanks

**Comment by riderodd** [comment]
+1

**Comment by Magiweb** [comment]
@BenjaminBini any chance of this (actually support for v5.4 or greate would be nice!)

**Comment by benjipott** [comment]
i work for this update

**Comment by Magiweb** [comment]
@benjipott great news, thank you! Do you have any idea when you might be finished with the update? I was very much hoping to use it towards the end of next week...

**Comment by pikilon** [comment]
+1

**Comment by benjipott** [comment]
starting now :)

**Comment by spuyet** [comment]
Awesome :+1:

**Comment by Magiweb** [comment]
:+1: :)

**Comment by benjipott** [comment]
you can view it on vjs-5 pr

**Comment by pikilon** [comment]
still not working i think...

Uncaught TypeError: Cannot read property 'extend' of undefined dailymotion.js : 24

**Comment by benjipott** [comment]
i remove dailymotion.js , it's old file.
make 
```
npm install
npm run dev
```

**Comment by benjipott** [comment]
#merged
